all:
  mooeditable:
    # Basic defaults
    default_width:                660
    default_height:               400
    default_config:               ''
    
    # Cleans up HTML pasted from Word (other text pasted without formatting)
    include_clean_paste:          true
    
    # Control tool bar options
    base_toolbar:                 'bold italic underline | insertunorderedlist insertorderedlist | undo redo | createlink unlink'
    default_extra_toolbar:        urlimage
    extra_js:                     []
    
    # Styling options
    base_css:                     'html { cursor: text; } body { font-family: Verdana, sans-serif; font-size: 11px; line-height: 13px; }'
    extra_css:                    []

    # Insert mooeditable script stuff in the page (false) or in a slot named
    # mooeditable_js where ever you like
    use_slots:                    false
    
  datepicker:
    # Default language for calendar picker
    default_locale:               en-GB
    
    # Insert datepicker script stuff in the page (false) or in a slot named
    # date_picker_js where ever you like
    use_slots:                    false
    
    # For use with the dropdowns
    default_date_display_format:  '%day% %month% %year%'
    deafult_time_display_format:  '%hour% %minute%'
    
    # Styling options
    picker_class:                 datepicker_light
    ## Location of default CSS theme files
    base_css_location:            '/sfMooToolsFormExtraPlugin/css/Datepicker' 
    ## If you want to use a custom calendar icon  
    calendar_icon:                '/sfMooToolsFormExtraPlugin/css/Datepicker/datepicker_light/icon_calendar.gif'
    ## Location of locale files for Datepicker (plugin just contains default - if overriding include default in this location too)    
    js_locale_location:           '/sfMooToolsFormExtraPlugin/js/Datepicker'        
    
  colourpicker:
    # Defaults
    ## this is the starting colour for the colour picker only
    default_colour:               '#ffffff'
    ## this is the colour the background is reset to after colour picked (should match your stylesheet)
    default_background_colour:    '#eeeeee'
    ## should the user be able to use the mouse scroll to change colour (this is a bit flaky)
    allow_scroll:                  true
  
    # Styling options
    ## Location of images used in CSS
    image_path:                   '/sfMooToolsFormExtraPlugin/css/mooRainbow/images/'
    ## Location of the image used to pick a colour - by default there are palette.png and rainbow.png
    picker_icon:                  '/sfMooToolsFormExtraPlugin/css/mooRainbow/images/palette.png'
    
    # Insert colourpicker script stuff in the page (false) or in a slot named
    # colour_picker_js where ever you like
    use_slots:                    false
    
  autocomplete:
    # Defaults
    ## Minimum length of search term before JSON request fired
    min_length:                   2
    ## Allow multiple tags to be selected by default - can be overridden on a case-by-case basis
    allow_multiple:               true
  
    # Insert autocomplete script stuff in the page (false) or in a slot named
    # autocomplete_js where ever you like
    use_slots:                    false
    